### ISSUE TITLE
value after props changed(like ajax call)

### ISSUE THREAD

**Issue by lesterzone** [imcnally/react-currency-masked-input#4]
First time Main component renders:
`var rate` equals `undefined` since it comes from an object property: `user.rate` and user = {};

```jsx
<CurrencyInput ref="rate" name="rate" onChange={this._rate} value={rate}/>
```

After ajax call resolves, UserStore updates `user` object and emit change. Then component renders again but, since: `Will use the value prop passed in as an initial value, but will take over from there.` value is not displayed and `var rate = REAL VALUE HERE`

I'm missing something?

Thanks for this awesome project.

**Comment by imcnally** [comment]
Hey Lester, you're very welcome! I'm happy people find it useful.

CurrencyMaskedInput takes the `value` prop you pass in, and uses that as the initial value. Then, the component takes over setting the value.

That means the component never checks the `value` prop again. So your asynchronous setting of the value prop isn't having an effect.

I believe if you do the ajax request, set the rate value in state, React will re-render CurrencyMaskedInput. It'd look something like:

```jsx
componentDidMount: function(){
   var _this = this;
   ajaxCall().done(function(rate){
      _this.setState({rate: rate});
  });
}

render: function(){
  return <CurrencyMaskedInput value={this.state.rate} />;
}
```

Give it a go, and let me know if that solves your dilemma.

**Comment by lesterzone** [comment]
Wow! That was a quick response, Thank you so much!

Unfortunately looks like it doesn't work: http://codepen.io/anon/pen/xGyxYO?editors=001

**Comment by imcnally** [comment]
I've got a fix outlined [here](http://codepen.io/imcnally/pen/yNRyBN). on `componentWillReceiveProps`, I can get the updated value.

I'll ping you when the work here's done!

**Comment by imcnally** [comment]
Fixed in a699707. The update's been published to npm, as version `0.0.11`.

Thanks for bringing this up Lester!

**Comment by lesterzone** [comment]
Thanks. Now it's working!

**Comment by imcnally** [comment]
:grinning:
